// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node prisma/seed.ts",
  },
  datasource: {
    // Allow CLI-only overrides without affecting the runtime pooled connection.
    url: process.env["PRISMA_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
